/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer */

#ifndef _Included_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
#define _Included_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
 * Method:    createBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer_createBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
 * Method:    getBuffer
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer_getBuffer
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
 * Method:    deleteBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer_deleteBuffers
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer
 * Method:    printBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_fsdataset_impl_JNIBuffer_printBuffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
